/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRecommendationsRouteImport } from './routes/ai-recommendations'
import { Route as AirQualityRouteImport } from './routes/air-quality'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnergyUsageRouteImport } from './routes/energy-usage'
import { Route as GreenCoverRouteImport } from './routes/green-cover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SustainabilityScoreRouteImport } from './routes/sustainability-score'
import { Route as TrafficMobilityRouteImport } from './routes/traffic-mobility'
import { Route as WasteManagementRouteImport } from './routes/waste-management'
import { Route as WaterManagementRouteImport } from './routes/water-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationsRoute = AiRecommendationsRouteImport.update({
  id: '/ai-recommendations',
  path: '/ai-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AirQualityRoute = AirQualityRouteImport.update({
  id: '/air-quality',
  path: '/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyUsageRoute = EnergyUsageRouteImport.update({
  id: '/energy-usage',
  path: '/energy-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenCoverRoute = GreenCoverRouteImport.update({
  id: '/green-cover',
  path: '/green-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityScoreRoute = SustainabilityScoreRouteImport.update({
  id: '/sustainability-score',
  path: '/sustainability-score',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficMobilityRoute = TrafficMobilityRouteImport.update({
  id: '/traffic-mobility',
  path: '/traffic-mobility',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteManagementRoute = WasteManagementRouteImport.update({
  id: '/waste-management',
  path: '/waste-management',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterManagementRoute = WaterManagementRouteImport.update({
  id: '/water-management',
  path: '/water-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/air-quality': typeof AirQualityRoute
  '/dashboard': typeof DashboardRoute
  '/energy-usage': typeof EnergyUsageRoute
  '/green-cover': typeof GreenCoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sustainability-score': typeof SustainabilityScoreRoute
  '/traffic-mobility': typeof TrafficMobilityRoute
  '/waste-management': typeof WasteManagementRoute
  '/water-management': typeof WaterManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/air-quality': typeof AirQualityRoute
  '/dashboard': typeof DashboardRoute
  '/energy-usage': typeof EnergyUsageRoute
  '/green-cover': typeof GreenCoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sustainability-score': typeof SustainabilityScoreRoute
  '/traffic-mobility': typeof TrafficMobilityRoute
  '/waste-management': typeof WasteManagementRoute
  '/water-management': typeof WaterManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRoute
  '/air-quality': typeof AirQualityRoute
  '/dashboard': typeof DashboardRoute
  '/energy-usage': typeof EnergyUsageRoute
  '/green-cover': typeof GreenCoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sustainability-score': typeof SustainabilityScoreRoute
  '/traffic-mobility': typeof TrafficMobilityRoute
  '/waste-management': typeof WasteManagementRoute
  '/water-management': typeof WaterManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-recommendations'
    | '/air-quality'
    | '/dashboard'
    | '/energy-usage'
    | '/green-cover'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/sustainability-score'
    | '/traffic-mobility'
    | '/waste-management'
    | '/water-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-recommendations'
    | '/air-quality'
    | '/dashboard'
    | '/energy-usage'
    | '/green-cover'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/sustainability-score'
    | '/traffic-mobility'
    | '/waste-management'
    | '/water-management'
  id:
    | '__root__'
    | '/'
    | '/ai-recommendations'
    | '/air-quality'
    | '/dashboard'
    | '/energy-usage'
    | '/green-cover'
    | '/login'
    | '/register'
    | '/reports'
    | '/settings'
    | '/sustainability-score'
    | '/traffic-mobility'
    | '/waste-management'
    | '/water-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRecommendationsRoute: typeof AiRecommendationsRoute
  AirQualityRoute: typeof AirQualityRoute
  DashboardRoute: typeof DashboardRoute
  EnergyUsageRoute: typeof EnergyUsageRoute
  GreenCoverRoute: typeof GreenCoverRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SustainabilityScoreRoute: typeof SustainabilityScoreRoute
  TrafficMobilityRoute: typeof TrafficMobilityRoute
  WasteManagementRoute: typeof WasteManagementRoute
  WaterManagementRoute: typeof WaterManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendations': {
      id: '/ai-recommendations'
      path: '/ai-recommendations'
      fullPath: '/ai-recommendations'
      preLoaderRoute: typeof AiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-quality': {
      id: '/air-quality'
      path: '/air-quality'
      fullPath: '/air-quality'
      preLoaderRoute: typeof AirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-usage': {
      id: '/energy-usage'
      path: '/energy-usage'
      fullPath: '/energy-usage'
      preLoaderRoute: typeof EnergyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-cover': {
      id: '/green-cover'
      path: '/green-cover'
      fullPath: '/green-cover'
      preLoaderRoute: typeof GreenCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability-score': {
      id: '/sustainability-score'
      path: '/sustainability-score'
      fullPath: '/sustainability-score'
      preLoaderRoute: typeof SustainabilityScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic-mobility': {
      id: '/traffic-mobility'
      path: '/traffic-mobility'
      fullPath: '/traffic-mobility'
      preLoaderRoute: typeof TrafficMobilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste-management': {
      id: '/waste-management'
      path: '/waste-management'
      fullPath: '/waste-management'
      preLoaderRoute: typeof WasteManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-management': {
      id: '/water-management'
      path: '/water-management'
      fullPath: '/water-management'
      preLoaderRoute: typeof WaterManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRecommendationsRoute: AiRecommendationsRoute,
  AirQualityRoute: AirQualityRoute,
  DashboardRoute: DashboardRoute,
  EnergyUsageRoute: EnergyUsageRoute,
  GreenCoverRoute: GreenCoverRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SustainabilityScoreRoute: SustainabilityScoreRoute,
  TrafficMobilityRoute: TrafficMobilityRoute,
  WasteManagementRoute: WasteManagementRoute,
  WaterManagementRoute: WaterManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
